using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Graphmatic.Interaction
{
    /// <summary>
    /// Represents a resource in a Graphmatic document.
    /// </summary>
    public class Resource : IXmlConvertible
    {
        /// <summary>
        /// Gets or sets the name of the resource in the document.
        /// </summary>
        public string Name
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the description of the resource.
        /// </summary>
        public string Description
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the name of the author of the resource.
        /// </summary>
        public string Author
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the date of creation of the resource.
        /// </summary>
        public DateTime CreationDate
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the uniquely-identifying GUID of the resource.
        /// </summary>
        public Guid Guid
        {
            get;
            protected set;
        }

        /// <summary>
        /// Gets or sets whether this resource is hidden in the document resource view.
        /// </summary>
        public bool Hidden
        {
            get;
            set;
        }

        /// <summary>
        /// Gets the string describing the type of the resource in the document.
        /// </summary>
        public virtual string Type
        {
            get
            {
                return "Resource";
            }
        }

        /// <summary>
        /// Gets or sets whether this resource has been removed from its parent document.<para/>
        /// This is used for resolving resource references to resources that have been removed from
        /// the document but not from memory.
        /// </summary>
        public bool Removed
        {
            get;
            set;
        }

        /// <summary>
        /// Initialize a new empty instance of the <c>Resource</c> class with a default name, and initialize the attributes identifying
        /// this resource in the file.
        /// </summary>
        public Resource()
        {
            Removed = false;
            InitializeIdentifyingAttributes();
            Name = "New " + Type;
        }

        /// <summary>
        /// Initializes the attributes that uniquely identify this Resource.
        /// <para/>
        /// This includes:
        /// <list type="bullet">
        ///     <item>
        ///         <term>Author</term>
        ///         <description>Given the value stored in the Username application setting.</description>
        ///     </item>
        ///     <item>
        ///         <term>CreationDate</term>
        ///         <description>Given the value returned by <c>DateTime.Now</c>.</description>
        ///     </item>
        ///     <item>
        ///         <term>Guid</term>
        ///         <description>Given a unique Guid generated by <c>Guid.NewGuid()</c>.</description>
        ///     </item>
        /// </list>
        /// </summary>
        public void InitializeIdentifyingAttributes()
        {
            Author = Properties.Settings.Default.Username;
            CreationDate = DateTime.Now;
            Guid = Guid.NewGuid();
        }

        /// <summary>
        /// Initialize a new empty instance of the <c>Graphmatic.Interaction.Resource</c> class from serialized XML data.
        /// </summary>
        /// <param name="xml">The XML data to use for deserializing this Resource.</param>
        public Resource(XElement xml)
        {
            Removed = false;
            Name = xml.Attribute("Name").Value;
            Author = xml.Attribute("Author").Value;
            CreationDate = DateTime.Parse(xml.Attribute("CreationDate").Value);
            Description = xml.Element("Description").Value;
            Guid = Guid.Parse(xml.Attribute("ID").Value);
            Hidden = xml.Attribute("Hidden") != null ?
                Boolean.Parse(xml.Attribute("Hidden").Value) :
                false;
        }

        public virtual Image GetResourceIcon(bool large)
        {
            return large ?
                Properties.Resources.Data32 :
                Properties.Resources.Data16;
        }

        public virtual XElement ToXml()
        {
            return new XElement("Resource",
                new XAttribute("Name", Name),
                new XAttribute("Author", Author),
                new XAttribute("CreationDate", CreationDate),
                new XAttribute("ID", Guid),
                new XAttribute("Hidden", Hidden),
                new XElement("Description", Description));
        }

        public XElement ToResourceReference()
        {
            return new XElement("Reference",
                new XAttribute("ID", Guid));
        }

        public override string ToString()
        {
            return Name;
        }

        public virtual void UpdateReferences(Document document)
        {

        }

        public virtual void ResourceModified(Resource resource, ResourceModifyType type)
        {

        }
    }
}
